name: Dart

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: dart-lang/setup-dart@v1

      - name: Install Melos
        run: dart pub global activate melos

      - name: Bootstrap packages
        run: melos bootstrap

      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        run: melos run test:dart 