name: server
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.3

dependencies:
  #mongo_dart: ^0.10.3 comes from fence_service
  logging: ^1.3.0
  # weebi's
  article_service:
    path: ../../packages/article_service
  contact_service:
    path: ../../packages/contact_service
  ticket_service:
    path: ../../packages/ticket_service
  fence_service:
    path: ../../packages/fence_service

dev_dependencies:
  test: ^1.25.8
  lints: ^5.0.0