name: fence_service
description: fence service for weebi server
version: 1.0.0
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  basic_utils: ^5.7.0
  collection: ^1.18.0
  crypto: ^3.0.3
  fixnum: ^1.1.0
  http: ^1.2.1
  mongo_dart: ^0.10.1
  protos_weebi: #^1.0.0
    path: ../protos/protos_weebi

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
