name: fence_service
description: fence service for weebi server
version: 1.0.1
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  basic_utils: ^5.7.0
  collection: ^1.18.0
  http: ^1.2.1
  # below are exported
  mongo_dart: ^0.10.3
  protos_weebi: #^1.0.4
    path: ../protos/protos_weebi
  models_weebi: ^1.1.6+1
  

dev_dependencies:
  test: ^1.25.8
  lints: ^5.0.0
