name: fence_service
description: fence service for weebi server
version: 1.0.1
publish_to: "none"
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  # below are weebi's kitchen
  protos_weebi: #^1.0.4
    path: ../protos/protos_weebi
  models_weebi: ^1.1.16

  mongo_pool: ^1.4.3    # exported
  mongo_dart: ^0.10.4   # exported
  logging: ^1.3.0  # exported

  collection: ^1.19.1
  pubspec_parse: ^1.3.0
  

dev_dependencies:
  test: ^1.26.3
  lints: ^5.0.0
