name: fence_service
description: fence service for weebi server
version: 1.0.1
publish_to: "none"
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  collection: ^1.18.0
  #basic_utils: ^5.7.0
  #http: ^1.2.1
  # below are exported
  mongo_pool: ^1.4.3
  mongo_dart: ^0.10.4
  mysql1: ^0.20.0
  logging: ^1.3.0
  protos_weebi: #^1.0.4
    path: ../protos/protos_weebi
  models_weebi: ^1.1.14+1
  

dev_dependencies:
  test: ^1.25.8
  lints: ^5.0.0
