name: protos_weebi
description: protos for weebi
version: 1.0.10+1
repository: https://github.com/weebi-com/weebi_server/
homepage: https://www.weebi.com

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  protobuf:  ^3.1.0
  # below are exported 
  grpc: ^4.0.1
  fixnum: ^1.1.1
  crypto: ^3.0.3

dev_dependencies:
  test: ^1.25.8
  lints: ^5.0.0