name: protos_weebi
description: protos for weebi
version: 1.4.0
repository: https://github.com/weebi-com/weebi_server/
homepage: https://www.weebi.com

environment:
  sdk: '>=3.12.2 <4.0.0'

dependencies:
  protobuf:  ^6.0.0
  cel: ^0.5.4+1
  # below are exported 
  grpc: ^5.1.0
  fixnum: ^1.1.1
  crypto: ^3.0.3

dev_dependencies:
  test: ^1.26.3
  lints: ^6.1.0