name: contact_service
description: A starting point for Dart libraries or applications.
version: 0.0.1
publish_to: 'none'
# homepage: https://www.example.com
# author: Your Name <email@example.com>

environment:
  sdk: ^3.3.3

dependencies:
  mongo_dart: ^0.10.1
  models_weebi: ^1.1.4
  protos_weebi:
    path: ../protos/protos_weebi
  fence_service:
    path: ../fence_service
  #fixnum: ^1.1.0

dev_dependencies:
  test: ^1.25.2
  lints: ^3.0.0
