name: contact_service
description: A starting point for Dart libraries or applications.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.3.3

dependencies:
  #mongo_dart comes from fence_service
  #fixnum comes from fence_service

  logging: ^1.3.0
  fence_service:
    path: ../fence_service

dev_dependencies:
  test: ^1.25.8
  lints: ^5.0.0
