name: Dart CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ping: 1})'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1
        
      - name: Install Melos
        run: dart pub global activate melos
        
      - name: Get dependencies
        run: dart pub get
        
      - name: Bootstrap workspace
        run: melos bootstrap
        
      - name: Analyze project source
        run: dart analyze
        
      - name: Wait for MongoDB
        run: |
          echo "Waiting for MongoDB to be ready..."
          for i in {1..30}; do
            if mongosh --eval "db.runCommand({ping: 1})" > /dev/null 2>&1; then
              echo "MongoDB is ready!"
              break
            fi
            echo "Waiting for MongoDB... attempt $i/30"
            sleep 2
          done
          
      - name: Run tests
        run: melos run test
        env:
          MONGO_DB_URI: mongodb://localhost:27017/local 