name: article_service
description: A starting point for Dart libraries or applications.
version: 0.0.1
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  mongo_dart: ^0.10.1
  models_weebi: ^1.1.4
  protos_weebi:
    path: ../protos/dartlang
  user_service:
    path: ../user_service
  #fixnum: ^1.1.0

dev_dependencies:
  test: ^1.25.2
  lints: ^3.0.0
